[project]
name = "jobsh"
version = "0.1.0"
description = "Local aggregator for German IT jobs"
authors = [
    { name = "julilili42", email = "Julian-jurcevic-2000@web.de" }
]
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
]

[project.scripts]
jobsh = "jobsh.cli:main"

[build-system]
requires = ["uv_build>=0.11.17,<0.12.0"]
build-backend = "uv_build"
